### PR TITLE
Final Commit for New Master Branch

### PR DESCRIPTION
**Pull request by nklansford**
Due to some initial oddities, the master branch was just now created. This commit is to merge develop into master.

### CODE REVIEW

**Comment by philschanely** [comment]
Thanks, @nklansford. Please do not merge until I can review and provide comments.

**Comment by philschanely** [comment]
- [ ] Nice logic and interaction setup in `ImageSlider`!

- [ ] Consider further organization of your images folder or using naming conventions to separate app-specific graphics like your nav arrows from content graphics like the image tiles.

- [ ] Just to tidy the appearance as a portfolio piece, consider centering the whole page and adding some white space above the `h1`.

- [ ] [Here](https://github.com/nklansford/react-image-slider/blob/a2c718874d0177ef4f3f5f918429ff92a2ff3295/src/data.js#L1) you can simplify this construct by simply doing:

  ```js
  export default [
      "./images/bork.png",
      "./images/coffee-mittens.png",
      "./images/snow-bubble.png",
      "./images/icesicles.png",
      "./images/person-in-snow.png",
      "./images/snow-bubble-2.png",
      "./images/snowflake.png",
      "./images/tweet.png",
      "./images/winter-scene.png",
  ];
  ```

- [ ] Depending on who you talk to, some would suggest that the `h1` belongs in `App.jsx`. Then, you can simplify the `ImageSlider` component:

  ```js
  render() {
    const { images } = this.props;
    const { currentIndex } = this.state;
    const currentImage = images[currentIndex];
    return (
      <div className="slider">
        <img onClick={this.indexBackward} className="slider_arrow slider_arrow--previous" alt="show previous" src="./images/previous-arrow.png" />
        <ul className="slider_list">
          <ImageSliderItem src={currentImage} />
        </ul>
        <img onClick={this.indexForward} className="slider_arrow slider_arrow--next" alt="show next" src="./images/next-arrow.png" />
      </div>
    );
  }
  ```

  Note as well that with this change, `App.jsx` can avoid extra markup using the JSX fragment wrapper like this:

  ```js
  function App() {
    return (
      <>
        <h1>Let it snow, let it snow</h1>
        <ImageSlider images={data}/>
      </>
    );
  }
  ```

  All the more, you could probably simplify all around, eliminate the sub-component `ImageSliderItem` and just do this in `ImageSlider`:

  ```js
  render() {
    const { images } = this.props;
    const { currentIndex } = this.state;
    const currentImage = images[currentIndex];
    return (
      <div className="slider">
        <img onClick={this.indexBackward} className="..." alt="show previous" src="./images/previous-arrow.png" />
        <img alt="" src={currentImage} />
        <img onClick={this.indexForward} className="..." alt="show next" src="./images/next-arrow.png" />
      </div>
    );
  }
  ```

  What you have certainly shows though towards componentizing separate pieces, so nothing wrong with it. Just may be more complex than needed.

- [ ] You probably don't need `App.css` anymore, so delete it and then remove [this line](https://github.com/nklansford/react-image-slider/blob/a2c718874d0177ef4f3f5f918429ff92a2ff3295/src/App.jsx#L3).

- [ ] [Here](https://github.com/nklansford/react-image-slider/blob/a2c718874d0177ef4f3f5f918429ff92a2ff3295/src/index.css#L1):

  - `img` and `ul` are likely more than needed for those selectors.
  - You'll find that the snake (underscore) convention is much less common than the kabob (hyphens) for separating words in class names. If, however, you're aiming for BEM then note we still use kabob for naming parts but its a `__` (double underscore) for element names such as `slider__arrow` and `slider__list`; for the list items you can probably use `slider__list-item` since `slider__list__item` would denote a grandchild element, something that's probably overkill for here. Alternatively, (and especially since the `item` is currently its own component) you could also name is `slider-item` or something else more "singular" or standalone. Regardless, if you make changes here be sure to sync up your markup in the components.

- [ ] On a related note, we'd typically break out our styles to separate style sheets to group them with the related component. Then with such a small app, what you have in `index.css` is fine, but you might see in other more complex apps that we have a `components` folder and in it you organize all your `.jsx` components along with an accompanying `.css` for each. So in your app, you might have a `ImageSlicer.css` alongside `ImageSlider.js` in which you place those styles that apply to the markup inside that component. If you also have `ImageSliderItem.jsx`  you might then have `ImageSliderItem.css` as well. We would also strive to align the name of those component files with the class names on the blocks inside them.

In the end, I have a [proposal refactor branch here](https://github.com/nklansford/react-image-slider/tree/pjs-demo-changes) that you can evaluate. I've not set it up as a PR so that you can choose what you want to do with the ideas revised there.

**Comment by nklansford** [comment]
@philschanely Thanks for the feedback! I will take a look through the proposed changes.

**Comment by nklansford** [comment]
@philschanely I implemented most of the changes. Let me know if I am set to merge. Thanks!

**Comment by nklansford** [comment]
Done! 👩‍💻

**Pull request merged**
